### ISSUE TITLE
[Suggestion] Append course creator to end of name

### ISSUE THREAD

**Issue by cstrife1** [Eltaurus-Lt/CourseDump2022#12]
There are often courses with almost exactly the same name, so it would be nice to know the course number and author/creator so it's easy to distinguish. Something like:

beginner-korean-[course number][author1]
beginners-korean-[course number][author2]

* Update

Here are 2 courses that will generate the exact same output file:

https://app.memrise.com/course/1114552/ihwa-hangugeo-3-1-ewha-korean-3-1/
https://app.memrise.com/course/1218462/ihwa-hangugeo-3-1-ewha-korean-3-1/

Thanks

**Comment by Eltaurus-Lt** [comment]
I can append course ids to the filenames, but adding the authors` names wouldn't be as easy as it seems. 
Memrise doesn't include them in the database with the learning items, the script is currently working with. So in order to retrieve the names one has to write a new parser for html sources of course pages.
Maybe it's better to just add the names by hand where needed since it doesn't take a lot of work and isn't crucial in most cases.

**Comment by cstrife1** [comment]
Course name would be good enough. It at least makes it easy at a glance to see where it came from.

**Comment by Eltaurus-Lt** [comment]
Did you mean course id?

**Comment by cstrife1** [comment]
Yes, course ID. Thanks!
